### ISSUE TITLE
Implement AVL Tree

### ISSUE THREAD

**Issue by ze413X** [ze413X/Stuff#10]
Implement an AVL Tree.

Requirements:
1. Must be a single header file.
2. Must be Template to allow storing different values.
3. Must come with test code to not only show off the tree but also test it further.

You can review the current RedBlackTree in the datastructures as an example. A lot of test cases has been removed there though.

**Comment by mvilkin** [comment]
Please check #15 for this.

**Comment by ze413X** [comment]
Solved in 0d91459 . Thank you mvilkin for your contribution!
