### ISSUE TITLE
Read/Write to file - both normally and binary

### ISSUE THREAD

**Issue by ze413X** [ze413X/Stuff#7]
Unlike examples online, I would prefer clear cut example which illustrates the proper way and the proper handling of both reading and writing to file.

**Comment by ze413X** [comment]
This issue is almost already implemented. It has to be added with keywords in order to create the file if it doesn't already exists. binary looks like it could go along with it. Some sources; https://stackoverflow.com/questions/23967697/if-file-exist-work-with-it-if-no-create-it

**Comment by fishavore** [comment]
@ze413X I went through your `ReadWriteToFile.h` file and the stackoverflow link to figure out what needs to be done for this issue. It seems that the `std::ofstream::open()` function creates a file when the file does not exist. Will you please tell me what specifically you want to accomplish with this so that I can try?

**Comment by ze413X** [comment]
I guess the only thing remaining is perhaps outputting text as binary jibberish so people cant view the content easily to then have a function to then put it back together. Honestly, I have not put much thought into this and might potentially be useless which might suffice with a comment. But like std::ios::binary to a .bin file with content. Along those lines. Showing how it is done I anyone would need to use it (preferably correctly). So people can go; "Aha! Alright, okay, now I get it."

**Comment by fishavore** [comment]
@ze413X thank you for answering my question! I came up with a solution to read and write a binary file. I hope you like it. btw, I just noticed that I used .dat instead of .bin. Please let me know if I should change that.
